/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ConnectStore.module.css";

function ConnectStore() {
  return (
    <section className={styles.connectStore}>
      <h2 className={styles.title}>Connect your store</h2>
      <div className={styles.storeLogos}>{/* Add store logos here */}</div>
    </section>
  );
}

export default ConnectStore;
