/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./FeatureSection.module.css";

const features = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/7bf0c4f2ca0770c30f2a41d63ffd1bf3216d8a158972290e9895d48e076c3c2c?placeholderIfAbsent=true&apiKey=b54505003cfa42f49d13ceb598b36320",
    title: "Higher Profits",
    description:
      "We offer some of the lowest prices in the industry because print providers continuously compete to win your business.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/001d9496e626c52288f027ace772d1a95c194b1586b2b888d6713f537d5070e5?placeholderIfAbsent=true&apiKey=b54505003cfa42f49d13ceb598b36320",
    title: "Robust Scaling",
    description:
      "Easily handle peak holiday seasons, with our wide network of partners and automatic routing functionality.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/001d9496e626c52288f027ace772d1a95c194b1586b2b888d6713f537d5070e5?placeholderIfAbsent=true&apiKey=b54505003cfa42f49d13ceb598b36320",
    title: "Best Selection",
    description:
      "With 900+ products and top quality brands, you can choose the best products for your business.",
  },
];

function FeatureSection() {
  return (
    <section className={styles.featureSection}>
      {features.map((feature, index) => (
        <div key={index} className={styles.feature}>
          <img src={feature.icon} alt="" className={styles.icon} />
          <h2 className={styles.title}>{feature.title}</h2>
          <p className={styles.description}>{feature.description}</p>
        </div>
      ))}
    </section>
  );
}

export default FeatureSection;
