/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Footer.module.css";

const footerSections = [
  {
    title: "Integrations",
    links: [
      "Shopify",
      "Etsy",
      "eBay",
      "Amazon",
      "TikTok Shop",
      "PrestaShop",
      "BigCommerce",
      "Wix",
      "WooCommerce",
      "Squarespace",
      "Printify API",
      "Printify Pop-Up Store",
      "Shutterstock",
    ],
  },
  {
    title: "Discover",
    links: [
      "Blog",
      "Guides",
      "Products",
      "Etsy print-on-demand",
      "Shopify print-on-demand",
      "Woocommerce print-on-demand",
      "Wix print-on-demand",
      "Squarespace print-on-demand",
      "Make Your Own Shirt",
      "Brands",
      "Pricing",
      "Shipping Rates",
      "Mockup Generator",
    ],
  },
  {
    title: "Start selling",
    links: [
      "Custom T-shirts",
      "Custom Hoodies",
      "Custom Mugs",
      "Custom Socks",
      "Custom Backpacks",
      "Custom Branding",
      "Sell on Etsy",
      "Sell on Social Media",
      "Free T-shirt Designs",
      "Custom Products",
      "Custom All-Over-Print Hoodies",
      "Start a Clothing Line",
      "Start POD Business",
      "Bulk Orders",
      "Transfering To Printify",
    ],
  },
  {
    title: "Printify",
    links: [
      "Print on Demand",
      "Print Providers",
      "Experts Program",
      "Printify Express Delivery",
      "Become a Partner",
      "About",
      "Printify Quality Promise",
      "Jobs",
      "Webinars",
      "Printing Profits Podcast",
      "Contact Us",
      "Affiliate",
      "Contact Sales",
      "POD Glossary",
      "Network Fulfillment Status",
      "Merchant Protection",
      "Security",
      "Sitemap",
    ],
  },
];

function Footer() {
  return (
    <footer className={styles.footer}>
      <div className={styles.footerContent}>
        {footerSections.map((section, index) => (
          <div key={index} className={styles.footerSection}>
            <h3 className={styles.sectionTitle}>{section.title}</h3>
            <ul className={styles.linkList}>
              {section.links.map((link, linkIndex) => (
                <li key={linkIndex}>
                  <a href="#" className={styles.footerLink}>
                    {link}
                  </a>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
      <div className={styles.legalSection}>
        <nav className={styles.legalNav}>
          <a href="#" className={styles.legalLink}>
            Intellectual Property Policy
          </a>
          <a href="#" className={styles.legalLink}>
            Terms of Service
          </a>
          <a href="#" className={styles.legalLink}>
            Privacy Policy
          </a>
          <a href="#" className={styles.legalLink}>
            Security
          </a>
        </nav>
        <p className={styles.copyright}>
          © 2024 Printify, Inc. All rights reserved.
        </p>
      </div>
    </footer>
  );
}

export default Footer;
