/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./HeroSection.module.css";

function HeroSection() {
  return (
    <section className={styles.heroSection}>
      <div className={styles.content}>
        <h1 className={styles.title}>
          Create and sell <br /> custom products
        </h1>
        <ul className={styles.features}>
          <li className={styles.feature}>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/55286ffdbbc99d320cd666fdb7b0ba9b29700b54eec730a7ece20a54de92f835?placeholderIfAbsent=true&apiKey=b54505003cfa42f49d13ceb598b36320"
              alt=""
              className={styles.icon}
            />
            <span>100% Free to use</span>
          </li>
          <li className={styles.feature}>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/f08d137b356d43748eacec72e5386e0d7cb1f3143a6c04df99b2839948aad98d?placeholderIfAbsent=true&apiKey=b54505003cfa42f49d13ceb598b36320"
              alt=""
              className={styles.icon}
            />
            <span>900+ High-Quality Products</span>
          </li>
          <li className={styles.feature}>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/5498cc952d3d6e6a475d98d1eee6794b375d4bebf20d2cfc8ba79c6a8a63ef71?placeholderIfAbsent=true&apiKey=b54505003cfa42f49d13ceb598b36320"
              alt=""
              className={styles.icon}
            />
            <span>Largest global print network</span>
          </li>
        </ul>
        <div className={styles.cta}>
          <a href="#" className={styles.primaryButton}>
            Start for free
          </a>
          <button className={styles.secondaryButton}>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/e007c2649fa6de0cd5666b22c155b7df8ca56ebdab76462c9c1ddf28e285c493?placeholderIfAbsent=true&apiKey=b54505003cfa42f49d13ceb598b36320"
              alt=""
              className={styles.buttonIcon}
            />
            How it works?
          </button>
        </div>
        <p className={styles.trust}>
          Trusted by over 8M sellers around the world
        </p>
      </div>
      <div className={styles.imageWrapper}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/db2e053fe563caee18efc34f36d86af5e334b98c10a418e68a8c06d2383643a2?placeholderIfAbsent=true&apiKey=b54505003cfa42f49d13ceb598b36320"
          alt="Custom product showcase"
          className={styles.heroImage}
        />
      </div>
    </section>
  );
}

export default HeroSection;
