/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./MakeMoneyRiskFree.module.css";

function MakeMoneyRiskFree() {
  return (
    <section className={styles.makeMoneyRiskFree}>
      <div className={styles.content}>
        <h2 className={styles.title}>Make Money, Risk-Free</h2>
        <p className={styles.subtitle}>
          You pay for fulfillment only when you make a sale
        </p>
        <div className={styles.example}>
          <div className={styles.row}>
            <span>You sell a t-shirt</span>
            <span>$ 30</span>
          </div>
          <div className={styles.row}>
            <span>You pay for its production</span>
            <span>$ 12</span>
          </div>
          <div className={styles.profit}>
            <span>Your profit</span>
            <span>$ 18</span>
          </div>
        </div>
        <a href="#" className={styles.startSellingButton}>
          Start selling
        </a>
        <p className={styles.features}>
          100% Free to use · 900+ Products · Largest print network
        </p>
      </div>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/9294c2b1f22509089299d15656cc24c27300116d88fe1ef78fe99b5dc05ef878?placeholderIfAbsent=true&apiKey=b54505003cfa42f49d13ceb598b36320"
        alt="Product showcase"
        className={styles.productImage}
      />
    </section>
  );
}

export default MakeMoneyRiskFree;
