/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import HeroSection from "./HeroSection";
import FeatureSection from "./FeatureSection";
import HowItWorks from "./HowItWorks";
import ConnectStore from "./ConnectStore";
import TalkToSales from "./TalkToSales";
import SocialProof from "./SocialProof";
import MakeMoneyRiskFree from "./MakeMoneyRiskFree";
import SocialLinks from "./SocialLinks";
import Footer from "./Footer";
import styles from "./PrintifyApp.module.css";

function PrintifyApp() {
  return (
    <div className={styles.printifyApp}>
      <Header />
      <main>
        <HeroSection />
        <FeatureSection />
        <HowItWorks />
        <ConnectStore />
        <TalkToSales />
        <SocialProof />
        <MakeMoneyRiskFree />
        <SocialLinks />
      </main>
      <Footer />
    </div>
  );
}

export default PrintifyApp;
