/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./SocialLinks.module.css";

const socialIcons = [
  "https://cdn.builder.io/api/v1/image/assets/TEMP/6a24e112b141d47e144cdde4e3d8d5549a7f422bb63a26b54d3a94d43c129bdc?placeholderIfAbsent=true&apiKey=b54505003cfa42f49d13ceb598b36320",
  "https://cdn.builder.io/api/v1/image/assets/TEMP/ec3f6cae51505f79d55c5f6e006a93f51eb941b98bbb92cc180d288c3e54e16a?placeholderIfAbsent=true&apiKey=b54505003cfa42f49d13ceb598b36320",
  "https://cdn.builder.io/api/v1/image/assets/TEMP/cb163a8a5fd12bc4e583a96c2d145c3428ce131ae32e0112343eb705d743e593?placeholderIfAbsent=true&apiKey=b54505003cfa42f49d13ceb598b36320",
  "https://cdn.builder.io/api/v1/image/assets/TEMP/b716474a9c02ad707c186cc04bf59f1310088d7a3b4bcfe421cb6067f86a46f5?placeholderIfAbsent=true&apiKey=b54505003cfa42f49d13ceb598b36320",
  "https://cdn.builder.io/api/v1/image/assets/TEMP/b1e385515826fe24a1ac7b141cf430bd16b502912c7b8ca1b29850e7180165b9?placeholderIfAbsent=true&apiKey=b54505003cfa42f49d13ceb598b36320",
  "https://cdn.builder.io/api/v1/image/assets/TEMP/ccd5b6ea07e088b3606448cb7ce7ed3f96bf30fc0719bfe7e3e39916604a8e0e?placeholderIfAbsent=true&apiKey=b54505003cfa42f49d13ceb598b36320",
  "https://cdn.builder.io/api/v1/image/assets/TEMP/598bcf6d60771e5b8b77a30f54c577999ebdd2c9bcab7d99696289924c80e810?placeholderIfAbsent=true&apiKey=b54505003cfa42f49d13ceb598b36320",
];

function SocialLinks() {
  return (
    <div className={styles.socialLinks}>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/ddd97df9ecfd1416bd8aafe78927c6109111d12187a4da07b23c02a83fae30c1?placeholderIfAbsent=true&apiKey=b54505003cfa42f49d13ceb598b36320"
        alt="Printify logo"
        className={styles.logo}
      />
      <div className={styles.icons}>
        {socialIcons.map((icon, index) => (
          <a key={index} href="#" className={styles.iconLink}>
            <img
              src={icon}
              alt={`Social media icon ${index + 1}`}
              className={styles.icon}
            />
          </a>
        ))}
      </div>
    </div>
  );
}

export default SocialLinks;
