/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./SocialProof.module.css";

const testimonials = [
  {
    name: "Robert A. Voltaire",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/9cef1453ce2ab6b4265911188383ae1ba493d0e3ee684889ecbe5dcef4531a93?placeholderIfAbsent=true&apiKey=b54505003cfa42f49d13ceb598b36320",
    rating: 5,
    text: "Printify has been an incredible service for us musicians unable to keep large amount of inventory - now we can create designs previously too expensive to print without having to have 1,000 shirts in our jam space. Thanks Printify!",
  },
  {
    name: "Quinten Barney",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/57f129d77f68af562d004d28917e60e625bfec45c57315c59145cc1392a25117?placeholderIfAbsent=true&apiKey=b54505003cfa42f49d13ceb598b36320",
    role: "Etsy Merchant",
    rating: 5,
    text: "We chose Printify because of their offerings as well as their incredibly low prices. After several years, we've come to find that their customer service is also top notch, and their platform just keeps getting better and better.",
  },
  {
    name: "Nikki",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/1f4bea3c38e0d428ab32431261a4591984b671181b8119384c2cd362c1dfe300?placeholderIfAbsent=true&apiKey=b54505003cfa42f49d13ceb598b36320",
    rating: 4,
    text: "Printify has been a amazing partner to work with as we grow our business, from the range of merch we can make for our customers to working with our Customer Service team (Hi Martin!) it's truly made the whole process a breeze.",
  },
];

function SocialProof() {
  return (
    <section className={styles.socialProof}>
      <h2 className={styles.title}>
        Trusted by over 8M sellers around the world
      </h2>
      <p className={styles.subtitle}>
        Whether you are just getting started or run an enterprise-level
        e-commerce business, we do everything we can to ensure a positive
        merchant experience.
      </p>
      <div className={styles.testimonials}>
        {testimonials.map((testimonial, index) => (
          <div key={index} className={styles.testimonial}>
            <img
              src={testimonial.image}
              alt={testimonial.name}
              className={styles.avatar}
            />
            <h3 className={styles.name}>{testimonial.name}</h3>
            {testimonial.role && (
              <p className={styles.role}>{testimonial.role}</p>
            )}
            <div className={styles.rating}>
              {[...Array(testimonial.rating)].map((_, i) => (
                <img
                  key={i}
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/3f8026050c141828d33a86a3314027324b84662048e254ca92c3dfa8205b789a?placeholderIfAbsent=true&apiKey=b54505003cfa42f49d13ceb598b36320"
                  alt="Star"
                  className={styles.star}
                />
              ))}
            </div>
            <p className={styles.text}>{testimonial.text}</p>
          </div>
        ))}
      </div>
    </section>
  );
}

export default SocialProof;
