/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./TalkToSales.module.css";

function TalkToSales() {
  return (
    <section className={styles.talkToSales}>
      <div className={styles.content}>
        <h2 className={styles.title}>
          Are you a large business looking for custom solutions?
        </h2>
        <a href="#" className={styles.salesButton}>
          Talk to sales
        </a>
      </div>
    </section>
  );
}

export default TalkToSales;
